package pl.sda.javapoz19.model;

public enum Specialization {

    NEUROLOGIST, UROLOGIST, DERMATOLOGIST, CARDIOLOGIST, ALLERGIST, ANESTHESIOLOGIST, ENDOCRINOLOGIST, HEMATOLOGIST
    , RADIOLOGIST, PEDIATRICIAN, INTERNIST, LARYNGOLOGIST;
}
